name: CoAP.NET
description: A CoAP framework in C#, providing CoAP-based services to .NET applications.
relative_permalinks: false
permalink: /:categories/:title/
repository: https://github.com/smeshlink/CoAP.NET
url: /CoAP.NET

version: 1.1.0
